# This workflow builds the package, installs it, and tests basic functionality

name: Build and Test Python Package

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-build-package:
    name: Test package build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Test build package
        uses: ./.github/actions/python-package-build
        with:
          test-package: "true"
          uv-version: "0.8.22"
          cli-test-command: "twyn --version"
          python-version: "3.10"
