# This workflow builds the package, installs it, and tests basic functionality

name: Build and Test Python Package

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-build-package:
    name: Test package build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Test build package
        uses: ./.github/actions/python-package-build
        with:
          test-package: "true"
          uv-version: "0.8.22"
          cli-test-command: "twyn --version"
          python-version: "3.10"
