name: Weekly download

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ vars.ELEMENTSINTERACTIVE_BOT_APP_ID }}
          private-key: ${{ secrets.ELEMENTSINTERACTIVE_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - name: Install the project
        run: uv sync --locked --only-group download --python 3.14

      - name: Download Pypi packages
        continue-on-error: true
        run: |
          uv run --no-project dependencies/scripts/download_packages.py download pypi

      - name: Download NPM packages
        continue-on-error: true
        run: |
          uv run --no-project dependencies/scripts/download_packages.py download npm

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to repo
        run: |
          git add .
          git commit -m "chore: Weekly update of trusted packages"
          git push origin HEAD:main
