name: Weekly download

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.ELEMENTSINTERACTIVE_BOT_APP_ID }}
          private-key: ${{ secrets.ELEMENTSINTERACTIVE_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

      - name: Install the project
        run: uv sync --locked --only-group download --python 3.14

      - name: Download Pypi packages
        continue-on-error: true
        run: |
          uv run --no-project dependencies/scripts/download_packages.py download pypi

      - name: Download NPM packages
        continue-on-error: true
        run: |
          uv run --no-project dependencies/scripts/download_packages.py download npm

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to repo
        run: |
          git add .
          git commit -m "chore: Weekly update of trusted packages"
          git push origin HEAD:main
